### ISSUE TITLE
Use `@firebase/testing` in tests rather than `firebase-admin`

### ISSUE THREAD

**Issue by capsudo** [benwinding/example-jest-firestore-triggers#1]
Hi first thanks for this repo it helped me a lot to figure out how to configure my tests to trigger the firestore functions. One thing though

Right now the example test uses `firebase-admin` to connect to the app :

```js
const db = getApp().firestore();
```
https://github.com/benwinding/example-jest-firestore-triggers/blob/18f1bdd41ec4d2657ee19201cb1948b2f0ef9c8c/test/index.spec.js#L15

```js
admin
    .initializeApp({
      // projectId: projectId,
      credential: admin.credential.cert(serviceAccount),
      // credential: admin.credential.applicationDefault(),
    });
```
https://github.com/benwinding/example-jest-firestore-triggers/blob/18f1bdd41ec4d2657ee19201cb1948b2f0ef9c8c/src/db.js#L10

> I was unable to get triggers working with @firebase/testing (hopefully this will change), so although firestore is running in the emulator, it's does require a real firebase project.

source : README.md

But in my testing it is working, although we do need we real firebase project, even if everything is running in the emulators (functions and firestore) except auth.

But for that you need to pass the credentials (serviceAccountKey.json) to the `initializeTestApp` config just like you do for `initializeApp`, alongside the projectId.
As soon as I set that I have the firestore triggers working in the emulator.

**Comment by benwinding** [comment]
Hi @didrip,
So you were able to get Firestore Triggers working with `@firebase/testing` app instances?
Cheers,
Ben

**Comment by capsudo** [comment]
Yes, here is how the connection to firebase instance is setup my `index.test.js` :

```js
const firebase = require('@firebase/testing');
const firebaseAdmin = require('firebase-admin'); // only needed to access the credentials object
const serviceAccount = require('../../service-account-key.json');
const projectId = 'real-app-id';
const firestore = firebase.initializeAdminApp(
{
	projectId: 'real-app-id',
	credential: firebaseAdmin.credential.cert(serviceAccount)
}).firestore();
```

and later some test (the firestore trigger cloud function creates documents in tags collections) :

```js
const mockDocument =
{
	title: 'test',
	tags: ['category A', 'category B', 'category C', 'category D'],
};

describe('firestore-triggers-tests', () =>
{
	beforeEach(async () => { await firebase.clearFirestoreData({ projectId: 'real-app-id' }); });

	const delay = 5000;

	test('tags are created after doc is added', async (done) =>
	{
		await firestore.collection(SOME_COLLECTION).add(mockDocument);

		console.log(`doc added, waiting ${delay / 1000}s (for cloud function to trigger)...`);
		await sleep(delay);

		const querySnapshot = await firestore.collection(TAGS_COLLECTION).where(FieldPath.documentId(), 'in', mockDocument.tags).get();
		expect(querySnapshot).toBeDefined();
		expect(querySnapshot.empty).toBe(false);
		expect(querySnapshot.docs.length).toBe(4); // 4 tags
		expect(querySnapshot.docs.map(tagSnapshot => tagSnapshot.data()))
		.toEqual(expect.arrayContaining([expect.objectContaining({ count: 1 })]));
		done();

	}, 5000 + delay); // change default timeout (5s by default)
});
```

**Comment by benwinding** [comment]
Wow thanks mate, I'll test it out and might update this repo to use that instead.
